version: '3.8'

services:

  moviedb:
    image: postgres:16.1-alpine3.19
    env_file:
      .env
    ports:
      - "5433:5432"
    volumes:
      - pg-data-core-controller:/var/lib/postgresql/data

  movieapp:
    build:
      context: .
      dockerfile: docker-files/app.Dockerfile
    restart: on-failure
    depends_on:
      - moviedb
    ports:
      - "8000:8000"
    env_file:
      .env

volumes:
  pg-data-core-controller:
